{{- if and (.Values.ingress.enabled) (.Values.ingress.tls) -}}
{{- $serviceName := include "gateway.fullname" . -}}
{{ $dot := . }}
{{- range $key, $host := .Values.ingress.tls -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $host.secretName }}
  labels:
    app.kubernetes.io/name: {{ $serviceName }}
    helm.sh/chart: "{{ $dot.Chart.Name }}-{{ $dot.Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/instance: {{ $dot.Release.Name }}
    app.kubernetes.io/managed-by: {{ $dot.Release.Service }}
type: "kubernetes.io/tls"
data:
  tls.crt: {{ $host.crt | b64enc }}
  tls.key: {{ $host.key | b64enc }}
{{- end -}}
{{- end -}}